### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by Minhui-princess** [Jiahuiqu/TMCFN-for-Hyperspectral-and-LiDAR-classification#1]
Dear author, I got an error saying "AttributeError: module 'utils' has no attribute 'get_data" while running the code, and I don't know how to handle it.  I sincerely appreciate your help.

**Comment by Jiahuiqu** [comment]
> Dear author, I got an error saying "AttributeError: module 'utils' has no attribute 'get_data" while running the code, and I don't know how to handle it. I sincerely appreciate your help.

Sorry, the file `utils.py` has been uploaded and updated. You could download the file and try again.

**Comment by Minhui-princess** [comment]
Thank you very much, it is running successfully.
