### ISSUE TITLE
Congratulations on your work being accepted !🥳

### ISSUE THREAD

**Issue by ZJier** [Jiahuiqu/TMCFN-for-Hyperspectral-and-LiDAR-classification#2]
1. When we run the code (demo_muufl.py: model.text_net.load_state_dict(torch.load("./text_encoder.pth"))  ##), we get an error: [Errno 2] No such file or directory: './text_encoder.pth'. In this project, there seems to be no “text_encoder.pth” file, how do we get it?🧐

2. In addition, In addition, we found "text_non_extended = ['Trees.', 'Mostly grass.', 'Mixed ground surface.', 'Dirt and sand.', 'Road.',  'Water.', 'Building Shadow.', 'Building.', 'Sidewalk.', 'Yellow curb.', 'Cloth panels.']" in the "demo_muufl.py" file, but not "text_extended = ['...',  '...', '...', '...', '...', ...]". Can you provide a full text description🫡, such as: 1) A sample of Mostly grass. 2) The color of Mostly grass is green and the texture is fine and uniform. 3) Mostly grass  often grows alongside trees, roads or sidewalks, even mixed with dirt and sand.

The important thing is, as I have just started exploring the CLIP model, there are many things I don't quite understand. If I have offended you in any way, please forgive me 🤪 : )

**Comment by Jiahuiqu** [comment]
> 1. When we run the code (demo_muufl.py: model.text_net.load_state_dict(torch.load("./text_encoder.pth"))  ##), we get an error: [Errno 2] No such file or directory: './text_encoder.pth'. In this project, there seems to be no “text_encoder.pth” file, how do we get it?🧐
> 2. In addition, In addition, we found "text_non_extended = ['Trees.', 'Mostly grass.', 'Mixed ground surface.', 'Dirt and sand.', 'Road.',  'Water.', 'Building Shadow.', 'Building.', 'Sidewalk.', 'Yellow curb.', 'Cloth panels.']" in the "demo_muufl.py" file, but not "text_extended = ['...',  '...', '...', '...', '...', ...]". Can you provide a full text description🫡, such as: 1) A sample of Mostly grass. 2) The color of Mostly grass is green and the texture is fine and uniform. 3) Mostly grass  often grows alongside trees, roads or sidewalks, even mixed with dirt and sand.
> 
> The important thing is, as I have just started exploring the CLIP model, there are many things I don't quite understand. If I have offended you in any way, please forgive me 🤪 : )

1. Please refer to the download link provided in the README.
2. The relevant code has been updated.

**Comment by ZJier** [comment]
Thank you very much for your reply, which is very critical and effective for me.🫡

**Comment by ZJier** [comment]
> > 1. When we run the code (demo_muufl.py: model.text_net.load_state_dict(torch.load("./text_encoder.pth"))  ##), we get an error: [Errno 2] No such file or directory: './text_encoder.pth'. In this project, there seems to be no “text_encoder.pth” file, how do we get it?🧐
> > 2. In addition, In addition, we found "text_non_extended = ['Trees.', 'Mostly grass.', 'Mixed ground surface.', 'Dirt and sand.', 'Road.',  'Water.', 'Building Shadow.', 'Building.', 'Sidewalk.', 'Yellow curb.', 'Cloth panels.']" in the "demo_muufl.py" file, but not "text_extended = ['...',  '...', '...', '...', '...', ...]". Can you provide a full text description🫡, such as: 1) A sample of Mostly grass. 2) The color of Mostly grass is green and the texture is fine and uniform. 3) Mostly grass  often grows alongside trees, roads or sidewalks, even mixed with dirt and sand.
> > 
> > The important thing is, as I have just started exploring the CLIP model, there are many things I don't quite understand. If I have offended you in any way, please forgive me 🤪 : )
> 
> 1. Please refer to the download link provided in the README.
> 2. The relevant code has been updated.


Thank you very much for your reply, which is very critical and effective for me.🫡
