### ISSUE TITLE
Expected accuracy

### ISSUE THREAD

**Issue by Minhui-princess** [Jiahuiqu/TMCFN-for-Hyperspectral-and-LiDAR-classification#3]
We're sorry to bother you again. Could we get the detailed parameter settings and related files on the Trento and 2013Houston datasets? Files we set up ourselves cannot achieve the expected accuracy, so we ask for your help in pursuing the rigor of experiments. In addition, are the FLOPs of this model 23G when batchsize=1? If we are wrong, we hope you will be able to correct us. Best wishes.

**Comment by Jiahuiqu** [comment]
The relevant code has been updated.
